-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table webpage.artikel
CREATE TABLE IF NOT EXISTS `artikel` (
  `id_artikel` int NOT NULL AUTO_INCREMENT,
  `tanggal` timestamp NOT NULL,
  `judul` varchar(300) NOT NULL,
  `penulis` varchar(300) NOT NULL,
  `kategori` varchar(300) NOT NULL,
  `isi` text NOT NULL,
  `gambar` varchar(300) NOT NULL,
  PRIMARY KEY (`id_artikel`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table webpage.artikel: ~4 rows (approximately)
INSERT INTO `artikel` (`id_artikel`, `tanggal`, `judul`, `penulis`, `kategori`, `isi`, `gambar`) VALUES
	(2, '2024-06-09 09:40:38', 'Nganjuk: Jejak Sejarah dan Asal Usul Nama', 'sivanafrd', '1', '<p><strong>Jejak Sejarah dan Asal Usul Nama</strong></p><p style="text-align:justify;">Asal usul nama Nganjuk berasal dari peristiwa sejarah yang terjadi pada masa Kerajaan Medang di Jawa Tengah. Pada saat itu, kerajaan mengalami kemunduran akibat perang antara wangsa Sriwijaya dan Sanjaya serta letusan Gunung Merapi. Raja Wawa dari wangsa Sanjaya kemudian memindahkan ibu kota kerajaan Medang. Keturunannya, Rakai i Hino Pu Sindok, memimpin pelarian ke arah timur Gunung Lawu dan Wilis.</p><p style="text-align:justify;">Di antara Gunung Lawu dan Wilis, Pu Sindok dan pasukannya mendapat perlindungan dari Samgat Pu Anjuk Ladang yang memimpin daerah Kakatikan Sri Jayamerta. Pu Sindok memberikan penghargaan kepada Samgat Pu Anjuk Ladang dan masyarakat Kakatikan Sri Jayamerta dengan memberikan status Sima swantantra, yaitu daerah otonomi dengan pengaturan pajak sendiri. Pemberian ini ditandai dengan prasasti tugu kemenangan berbentuk curik, senjata dewa Wisnu yang disebut Jayastamba, serta candi Kabaktyan Sang Hyang Prasada Sri Jayamerta. Prasasti ini bertanggal hari Senin Pon, 10 April 937 Masehi, menurut penanggalan candra sengkala mêmêt naga 8, cakra 5, sangkha 9.</p><p style="text-align:justify;">Dengan pemberian status Sima swantantra ini, daerah Kakatikan Sri Jayamerta berubah nama menjadi wilayah Sima Pu Anjuk Ladang. Nama "Nganjuk" kemudian diyakini berasal dari nama Anjuk Ladang, yang merupakan bentuk penghormatan terhadap Sanggat/Sang Pamegat Pu Anjuk Ladang yang memimpin daerah tersebut pada waktu itu. Sejak itu, Nganjuk tumbuh dan berkembang sebagai sebuah kota dengan sejarah yang kaya, mencerminkan perjuangan dan keberanian masyarakatnya dalam melindungi dan mempertahankan wilayah mereka.<br>&nbsp;</p>', 'gambar/sejarah.jpg'),
	(3, '2024-06-09 09:41:15', 'Candi Ngetos: Jejak Sejarah Keagungan Kerajaan Majapahit', 'sivanafrd', '2', '<p><strong>Jejak Sejarah Keagungan Kerajaan Majapahit</strong></p><p style="text-align:justify;">Kabupaten Nganjuk, Jawa Timur, tidak hanya terkenal dengan keindahan alamnya, tetapi juga kaya akan warisan bersejarah yang mengagumkan. Salah satu situs bersejarah yang tak boleh dilewatkan adalah Candi Ngetos, tempat yang menyimpan sejarah panjang Kerajaan Majapahit. Candi Ngetos terletak di Desa Ngetos, Kecamatan Ngetos, sekitar 17 kilometer ke arah selatan dari pusat Kabupaten Nganjuk. Candi ini bukan hanya sebuah tempat ibadah, tetapi juga menjadi makam Raja Hayam Wuruk dari Kerajaan Majapahit. Dibangun pada abad ke-15, candi ini menghadap ke barat dan memiliki dimensi yang mengesankan: panjang 9,1 meter, tinggi 10 meter, dengan tangga naik yang lebar 3,75 meter dan tinggi 2,47 meter.</p><p style="text-align:justify;">Menurut Aris Trio Effendi, juru pelihara Candi Ngetos, tempat ini sebenarnya dikenal dengan nama Candi Paramasakapura, yang kemudian dikenal sebagai Candi Ngetos sesuai dengan nama Desa Ngetos di sekitarnya. "Candi Pendharmaan ini adalah tugu peringatan kematian seorang raja. Pada tahun 1389, Hayam Wuruk meninggal dunia, dan candi ini dibangun untuk menghormatinya," jelas Aris. Pengunjung dari berbagai daerah, bahkan luar negeri, sering datang untuk mengagumi keindahan dan sejarah yang terkandung di dalam Candi Ngetos. "Kami menerima banyak pengunjung dari luar kota seperti Bali, Jogja, dan Solo, serta sejumlah besar wisatawan dari mancanegara," tambah Aris. Pengunjung terjauh bahkan datang dari luar negeri, yang banyaknya adalah sejarawan yang tertarik untuk menggali lebih dalam kebudayaan dan sejarah lokal.</p><p style="text-align:justify;">Candi Ngetos, dengan keindahannya yang abadi dan sejarahnya yang kaya, tetap menjadi salah satu warisan budaya yang patut dijaga dengan baik oleh masyarakat dan pemerintah setempat. Selain sebagai objek wisata yang menarik, candi ini juga menjadi saksi bisu kejayaan Kerajaan Majapahit, yang tetap menginspirasi pengunjung dari berbagai belahan dunia.</p>', 'gambar/candi-ngetos.jpg'),
	(4, '2024-06-09 15:40:06', 'Nganjuk Peringati Tradisi Boyong Natapraja dan Sedekah Bumi ke-144', 'alsyaml', '3', '<p style="text-align:justify;">Pemerintah Daerah Kabupaten Nganjuk menggelar peringatan hari boyongan pemerintahan dari Kabupaten Berbek ke Nganjuk yang ke-144, bersamaan dengan perayaan Sedekah Bumi. Acara ini berlangsung pada Kamis (06/06/2024), dengan partisipasi seluruh Organisasi Perangkat Daerah (OPD) di Kabupaten Nganjuk.</p><p style="text-align:justify;">Upacara Boyong Natapraja dimulai dari Pendopo Alun-Alun Berbek menuju Pendopo KRT. Soesro Koesoema Kabupaten Nganjuk. Pj. Bupati Nganjuk, Sri Handoko Taruna, bersama Forkopimda Nganjuk, jajaran OPD, serta elemen masyarakat termasuk sejarawan dan pegiat seni budaya, turut hadir memeriahkan acara tersebut. Kirab Boyongan tahun ini lebih meriah dengan keterlibatan semua pejabat Pemerintah Kabupaten Nganjuk, pengusaha, dan tokoh masyarakat. Mereka mengenakan pakaian lurik dan diarak menggunakan dokar dari Berbek menuju Nganjuk.</p><p style="text-align:justify;">Prosesi Boyong Natapraja berlangsung dalam delapan sesi dari pukul 12.30 hingga 17.00 WIB, dengan beberapa pemberhentian penting. Dimulai dengan persiapan pusaka dari Balai Desa Berbek yang dipindahkan ke Pendopo Berbek, dilanjutkan dengan prosesi Susulan dan Sasrahan. Upacara Pembukaan Boyong Natapraja dimulai dengan tarian Bedoyo, kemudian pemberangkatan Boyong menggunakan kereta kuda menuju Stadion Anjuk Ladang. Dari sana, kirab budaya dilanjutkan dari Anjuk Ladang menuju Taman Nyawiji. Para peserta boyong turun dari kereta kuda dan melakukan Lampahan Natapraja menuju gerbang Tugu. Setelah sampai di depan Tugu, dilakukan prosesi Bukak Lawang dan Penyerahan Pusaka yang diakhiri dengan Sedekah Bumi.</p><p style="text-align:justify;">Perayaan Boyong Natapraja dan Sedekah Bumi Kabupaten Nganjuk tahun ini dirasakan oleh seluruh masyarakat Nganjuk. Semua pihak yang terlibat merasakan kebersamaan dan kegembiraan, dengan tradisi Purakan Gunungan sebagai simbol penyatuan rakyat dalam semangat membangun negeri, merayakan hasil panen, dan mengungkapkan rasa syukur yang mendalam.</p>', 'gambar/natapraja.jpg'),
	(7, '2024-06-09 20:11:20', 'Jolotundo Edupark: Wisata Back-to-Nature ala Korea di Nganjuk', 'alsyaml', '2', '<p style="text-align:justify;">Nuansa pergantian tahun baru 2024 masih terasa di Nganjuk, di mana masyarakat memanfaatkan libur panjang untuk berlibur ke tempat-tempat wisata lokal, termasuk Jolotundo Edupark. Terletak di kaki Gunung Liman, Desa Banjulan, dan melintasi hutan Kecamatan Loceret, Jolotundo Edupark merupakan destinasi wisata baru yang dapat dicapai dalam setengah jam perjalanan dari alun-alun Nganjuk.</p><p style="text-align:justify;">Pengunjung dapat mengakses Jolotundo Edupark dengan kendaraan pribadi, membayar tiket masuk Rp5 ribu untuk mobil dan Rp2 ribu untuk motor. Wisata ini beroperasi Rabu-Kamis (09.00-16.00 WIB) dan Jumat-Minggu (09.00-20.00 WIB), dengan pembatasan operasional karena faktor mobilitas dan pengembangan fasilitas.</p><h3 style="text-align:justify;">Ada apa aja di Jolotundo?</h3><p style="text-align:justify;">Jolotundo Edupark menawarkan suasana alami dengan terasering untuk mencegah longsor dan pepohonan pinus yang menjulang tinggi. Konsep back-to-nature ditujukan untuk mereka yang ingin rehat dari hiruk-pikuk kota dan puasa media sosial, mengingat keterbatasan sinyal di area ini. Berdekatan dengan wisata air terjun Roro Kuning, Jolotundo Edupark memiliki arena air sebagai daya tarik utama.</p><p style="text-align:justify;">Meskipun pembangunan arena bermain anak dan tempat makan masih berlangsung, tempat ini ramai dikunjungi selama liburan akhir tahun. Pengunjung tidak diperbolehkan membawa makanan dan minuman dari luar untuk mendukung pembangunan area wisata melalui menu-menu yang disediakan di kafe.</p><p style="text-align:justify;">Di kafe, pengunjung dapat menikmati berbagai menu dengan harga mulai dari Rp4 ribu hingga Rp30 ribu. Reservasi tempat duduk di area taman pinus atau tenda dekat sungai tersedia, dengan akses melalui jembatan gantung yang hanya dapat dilalui 10 orang secara bergantian.</p><p style="text-align:justify;">Untuk pengunjung yang ingin menginap, tersedia tenda dengan tarif Rp250 ribu per malam pada weekdays, Rp300 ribu pada weekend di area pinus, dan Rp350 ribu di area sungai. Fasilitas menginap termasuk kasur, selimut, lampu tenda, stop kontak, pengharum tenda, sarapan, dan jasa bongkar pasang tenda.</p><p style="text-align:justify;">Pelestarian lingkungan dan promosi wisata daerah terus digiatkan, terutama setelah pandemi. Dukung perekonomian lokal dengan mengunjungi tempat wisata, karena yang melokal yang mendunia!</p>', 'gambar/jolotundo.jpg'),
	(9, '2024-06-20 11:26:58', 'Prima Swalayan: Destinasi Belanja Terlengkap di Nganjuk', 'sivanafrd', '5', '<p>Prima Swalayan adalah supermarket terlengkap di Nganjuk yang telah menjadi pilihan utama warga setempat untuk memenuhi berbagai kebutuhan sehari-hari. Berlokasi di Jl. Yos Sudarso No.26-30, Payaman, Kec. Nganjuk, Kab. Nganjuk, Prima Swalayan menawarkan pengalaman belanja yang nyaman dan lengkap.</p><h5>Beragam Produk yang Ditawarkan</h5><p>&nbsp;</p><p>Prima Swalayan menyediakan berbagai kebutuhan pokok, mulai dari bahan makanan seperti sayur-sayuran segar, buah-buahan, daging, dan ikan, hingga makanan cepat saji yang siap dinikmati. Tidak hanya itu, swalayan ini juga menawarkan segala macam barang keperluan rumah tangga, baik yang digunakan di dalam rumah seperti peralatan dapur dan kebersihan, maupun yang digunakan di luar rumah seperti peralatan kebun dan perawatan kendaraan.</p><h5>Layanan Jasa Antar Barang Gratis</h5><p>&nbsp;</p><p>Salah satu keunggulan Prima Swalayan adalah layanan jasa antar barang gratis dengan pembelian minimal Rp100 ribu. Layanan ini sangat membantu bagi pelanggan yang tidak memiliki waktu untuk membawa belanjaan sendiri, atau yang memiliki belanjaan dalam jumlah besar. Pelanggan hanya perlu berbelanja dengan nominal yang telah ditentukan, dan barang akan diantar langsung ke rumah mereka.</p><h5>Jam Operasional</h5><p>&nbsp;</p><p>Prima Swalayan beroperasi setiap hari mulai pukul 09.00 hingga 21.00 WIB. Jam operasional yang fleksibel ini memberikan keleluasaan bagi pelanggan untuk berbelanja kapan saja, baik di pagi hari sebelum memulai aktivitas maupun di malam hari setelah selesai bekerja.</p><h5>Kenyamanan dan Kebersihan</h5><p>&nbsp;</p><p>Dengan penataan yang rapi dan lingkungan yang bersih, Prima Swalayan memastikan kenyamanan pelanggan saat berbelanja. Setiap lorong toko diatur sedemikian rupa agar memudahkan pelanggan menemukan barang yang mereka butuhkan. Selain itu, staf yang ramah dan siap membantu juga menjadi nilai tambah bagi swalayan ini.</p><p><strong>Alamat</strong> : Jl. Yos Sudarso No.26-30, Payaman, Kec. Nganjuk, Kab. Nganjuk &nbsp;</p>', 'gambar/primafix.jpg'),
	(10, '2024-06-20 11:35:59', 'Asem-asem Kambing: Kuliner Khas Nganjuk yang Menggugah Selera', 'aisrisna', '6', '<p style="text-align:justify;">Nganjuk, sebuah kota di Jawa Timur yang terkenal dengan berbagai kuliner khasnya, memiliki satu hidangan yang wajib dicoba bagi para pecinta makanan tradisional, yaitu Asem-asem Kambing. Hidangan ini menawarkan cita rasa unik yang memadukan daging kambing dengan bumbu rempah dan daun kedondong, menciptakan sensasi rasa asam dan segar yang khas.</p><p style="text-align:justify;"><strong>Kelezatan Asem-asem Kambing</strong><br>Asem-asem Kambing merupakan salah satu kuliner yang paling dicari di Nganjuk. Sesuai dengan namanya, hidangan ini berbahan dasar daging kambing yang dimasak dengan daun kedondong dan bumbu rempah-rempah. Proses memasak yang telaten membuat daging kambing menjadi empuk dan lezat, sementara daun kedondong memberikan rasa asam yang menyegarkan. Kombinasi ini menjadikan Asem-asem Kambing sangat cocok disantap saat siang hari, terutama dalam kondisi cuaca yang panas.</p><p style="text-align:justify;"><strong>Warung Makan Bu Harsuni: Tempat Terbaik untuk Menikmati Asem-asem Kambing</strong><br>Bagi yang ingin mencicipi kelezatan Asem-asem Kambing, Warung Makan Bu Harsuni adalah tempat yang sangat direkomendasikan. Warung ini berlokasi di Jalan Gondang-Ngluyu, Putuk Wetan, Gampeng. Warung Bu Harsuni sudah terkenal di kalangan warga setempat maupun wisatawan sebagai tempat terbaik untuk menikmati hidangan tradisional ini.</p><p style="text-align:justify;"><strong>Pengalaman Kuliner di Warung Makan Bu Harsuni</strong><br>Mengunjungi Warung Makan Bu Harsuni tidak hanya tentang menikmati makanan lezat, tetapi juga merasakan suasana makan yang khas dan ramah. Warung ini menawarkan suasana yang sederhana namun nyaman, dengan pelayanan yang hangat dari pemilik dan stafnya. Pengunjung dapat menikmati Asem-asem Kambing dengan harga yang terjangkau, menjadikannya pilihan yang pas untuk makan siang bersama keluarga atau teman.</p><p style="text-align:justify;"><strong>Cara Menuju Warung Makan Bu Harsuni</strong><br>Warung Makan Bu Harsuni mudah dijangkau karena berada di jalur utama Jalan Gondang-Ngluyu. Bagi pengunjung yang menggunakan kendaraan pribadi, tersedia area parkir yang cukup luas. Sementara itu, bagi yang menggunakan transportasi umum, warung ini dapat dicapai dengan berbagai angkutan lokal yang melewati daerah tersebut.</p><p style="text-align:justify;"><br>Asem-asem Kambing adalah salah satu kuliner khas Nganjuk yang tidak boleh dilewatkan. Dengan kombinasi rasa asam, segar, dan daging kambing yang empuk, hidangan ini menawarkan pengalaman kuliner yang unik dan memuaskan. Warung Makan Bu Harsuni di Jalan Gondang-Ngluyu, Putuk Wetan, Gampeng, adalah tempat yang tepat untuk menikmati kelezatan Asem-asem Kambing. Jadi, jika Anda berkunjung ke Nganjuk, jangan lupa untuk menyempatkan diri mencicipi kuliner yang satu ini.</p>', 'gambar/asemasem.jpg');

-- Dumping structure for table webpage.kategori
CREATE TABLE IF NOT EXISTS `kategori` (
  `id_kategori` int NOT NULL AUTO_INCREMENT,
  `nama_kategori` varchar(50) NOT NULL,
  `keterangan` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id_kategori`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table webpage.kategori: ~4 rows (approximately)
INSERT INTO `kategori` (`id_kategori`, `nama_kategori`, `keterangan`) VALUES
	(1, 'sejarah', 'Artikel yang membahas tentang sejarah dan budaya lokal'),
	(2, 'wisata', 'Artikel yang membahas tentang wisata yang ada'),
	(3, 'event', 'Artikel yang membahas tentang acara lokal yang diadakan secara berkala'),
	(5, 'belanja', 'Artikel yang membahas tentang informasi tempat belanja'),
	(6, 'kuliner', 'Kategori ini mencakup informasi tentang tempat makan terbaik di Nganjuk, mulai dari restoran, kafe, hingga warung makan lokal.');

-- Dumping structure for table webpage.kontributor
CREATE TABLE IF NOT EXISTS `kontributor` (
  `id_kontributor` int NOT NULL AUTO_INCREMENT,
  `id_artikel` int NOT NULL,
  `id_kategori` int NOT NULL,
  `id_penulis` int NOT NULL,
  PRIMARY KEY (`id_kontributor`) USING BTREE,
  KEY `FK_kontributor_artikel` (`id_artikel`),
  KEY `FK_kontributor_kategori` (`id_kategori`),
  KEY `FK_kontributor_penulis` (`id_penulis`),
  CONSTRAINT `FK_kontributor_artikel` FOREIGN KEY (`id_artikel`) REFERENCES `artikel` (`id_artikel`),
  CONSTRAINT `FK_kontributor_kategori` FOREIGN KEY (`id_kategori`) REFERENCES `kategori` (`id_kategori`),
  CONSTRAINT `FK_kontributor_penulis` FOREIGN KEY (`id_penulis`) REFERENCES `penulis` (`id_penulis`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table webpage.kontributor: ~0 rows (approximately)

-- Dumping structure for table webpage.penulis
CREATE TABLE IF NOT EXISTS `penulis` (
  `id_penulis` int NOT NULL AUTO_INCREMENT,
  `nama_penulis` varchar(50) NOT NULL,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id_penulis`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table webpage.penulis: ~2 rows (approximately)
INSERT INTO `penulis` (`id_penulis`, `nama_penulis`, `username`, `password`) VALUES
	(3, 'Alsy Amalia', 'alsyaml', '$2y$10$HP2tPoMe6n6G38ad0Z5NcOiq9Z4e.IJImDRvqXeKCExowTFRd0Cm2'),
	(4, 'Sivana Firdausy', 'sivanafrd', '$2y$10$Nd4TK14p7eciMW46KHdXhezY0wzfM/zxdk/VYRME8ffRs1ic1eMPi'),
	(5, 'Siti Wasi\'atul', 'stwasik', '$2y$10$Lv58V.a/G6awCf8zHWMmgu0PT9Aplf6QYy8N80D8FYtNGJ7VYNcve'),
	(6, 'Gusti Risna', 'aisrisna', '$2y$10$ueNqmslraG0dLdr3qXciAOTZSos0L7jTwCQSNxVHm6obWodrXT4Pe');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
